version: '3.8'

services:
  # 1. Serviciul de AI (Python)
  ai-service:
    build: ./ai-service-python
    container_name: athletica-ai-python
    ports:
      - "8006:8006"
    # Citim cheia de AI din .env din root
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: always

  # 2. Backend-ul Java (Spring Boot)
  java-backend:
    build: ./backend-java/app
    container_name: athletica-ai-java
    ports:
      - "8080:8080"
    depends_on:
      - ai-service
    environment:
      - DOCKER_ENV=true
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - AI_SERVICE_URL=http://ai-service:8006/predict
    restart: always

  # 3. Frontend-ul (Nginx)
  frontend:
    image: nginx:alpine
    container_name: athletica-ai-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend-web:/usr/share/nginx/html
    restart: always
